services:
  casdoor:
    image: casbin/casdoor:v1.846.0
    restart: always
    environment:
      driverName: mysql
      dataSourceName: user:letmein@tcp(192.168.50.237:3306)/
      dbName: db
    ports: # Host:Container
      - 8081:8000 # Dashboard

# start mysql first
# change ip